### ISSUE TITLE
problem with material-ui elements

### ISSUE THREAD

**Issue by leogoesger** [kentcdodds/react-testing-library#234]
- `react-testing-library` version: 5.3.1
- `react` version: 16.7.0-alpha.2
- `node` version: 10
- `npm` (or `yarn`) version: 6.1.0

### Relevant code or config:

```js
test('calls with user email and password', () => {
  const login = jest.fn();
  const error = null as any;

  const { getByLabelText, getByText } = render(
    <LoginForm login={login} error={error} />
  );

  const email = getByLabelText('Email');
  const password = getByLabelText('Password');
  email.value = 'test@test.com';
  password.value = 'password';
  fireEvent.click(getByText('Login'));

  expect(login).toHaveBeenCalledTimes(1);
  expect(login).toHaveBeenCalledWith({
      email: 'leoq91@gmail.com',
      password: 'password',
  });
});
```

// login-form
```js

export const LoginForm: FunctionComponent<IProps> = ({ login, error }) => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  return (
    <Paper>
      <form
        onSubmit={e => {
          e.preventDefault();
          return login({ email, password });
        }}
      >
        <TextField
          id="email"
          label="Email"
          onChange={e => setEmail(e.target.value)}
        />
        <TextField
          id="password"
          label="Password"
          type="password"
          onChange={e => setPassword(e.target.value)}
        />
        <LoginError error={error} />
        { /* <button type="submit">Login</button> This works...*/}
        <Button
          type="submit"
        >
          Login
        </Button>
      </form>
      <Divider />
      <Typography style={{ margin: '10px auto' }}>Forgot password?</Typography>
    </Paper>
  );
};

```

### What you did:

Writing my first test with material-ui for a login form.

https://codesandbox.io/s/lx5nl1839z

### What happened:

Test would not pass when I try to click on the submit button. BUT It works as expected if I use a regular button instead of a material ui Button.

**Comment by gnapse** [comment]
Does it work in the browser with the material-ui button?

Also, probably unrelated, but you should not set the input elements values with `element.value = '123'`. You should use `fireEvent.change(inputElement, { target: { value: '123' } })` instead.

It would help if you provided a ready-to-be-used reproduction repo, or better yet, a code sandbox.

**Comment by leogoesger** [comment]
added sandbox https://codesandbox.io/s/lx5nl1839z

**Comment by kentcdodds** [comment]
Hmm... If that's the case then this is a bug because it should bubble up from the span to the button. Anyone care to look into why that's not happening?

**Comment by dfcook** [comment]
The event is bubbling, if you add an onClick handler to the Button then that fires. The issue seems to be that a bubbled event does not then trigger form submission.

**Comment by kentcdodds** [comment]
Oh, that's interesting. I wonder what happens in a real browser... Hmmm...

**Comment by kentcdodds** [comment]
Alright! Anyone wanna [dig](https://kcd.im/dig) in jsdom to figure out what's going on? https://github.com/jsdom/jsdom/issues/2449

**Comment by kentcdodds** [comment]
A fix has been merged in jsdom. Hopefully it's released soon. Also hopefully Jest's version range of jsdom accepts the fix 🤞

There's nothing more we can do here, so I'll close this.

**Comment by ryanadhi** [comment]
I am still having the issue using MUI (material ui), I am expecting when clicking the 'login' button it will show the text of error helper. somehow the test does not show when I use `screen.debug()` 

Any suggestion? 

for context
```
    "@testing-library/jest-dom": "^5.16.4",
    "@testing-library/react": "^13.3.0",
    "@testing-library/user-event": "^14.2.5",
    "react": "^18.2.0",
```
