### ISSUE TITLE
fireEvent.keyPress not fire in test

### ISSUE THREAD

**Issue by zhaozhiming** [kentcdodds/react-testing-library#269]
- `react-testing-library` version: 5.4.4
- `react` version: 16.5.2
- `node` version:  10.0.0
- `npm` (or `yarn`) version: yarn 1.9.2

### Relevant code or config:

```js
  test("input key press correctly", () => { // failed
    const doSomething = jest.fn();
    const doOtherThing = jest.fn();
    const { container } = render(
      <App doSomething={doSomething} doOtherThing={doOtherThing} />
    );
    const input = getByTestId(container, "input");
    fireEvent.keyPress(input, { key: "Enter", code: 13 });
    expect(doSomething.mock.calls.length).toBe(1);
  });
```

### What you did:
run test

### What happened:
test failed

### Reproduction:
https://codesandbox.io/s/jrv9v845v

### Problem description:
When use fireEvent.keyPress, the input keyPress event not fired.
I found the doc  about this part of the content, but I don't know what different between the keyPress event and change event.  
![image](https://user-images.githubusercontent.com/1436694/51361932-997a5700-1b0c-11e9-8fd0-fffd1afce11e.png)

### Suggested solution:
I have no idea.

**Comment by baruchvlz** [comment]
I decided to dig into this a little bit. Adding `input.addEventListener('keypress', console.log);` shows that the event is indeed dispatched but for some reason React isn't calling the function.

**Comment by kentcdodds** [comment]
Awesome! Would anyone be willing to add a note about this in the docs?

**Comment by puemos** [comment]
I'm on it 😎

**Comment by baruchvlz** [comment]
Maybe have a fallback in the library where if the user has `code` and not `charCode` then set `charCode` to the value of `code`.

```javascript
if (init.code && !init.charCode) {
  init.charCode = init.code;
}
```
I feel this is too much coding for failure, but I still wanted to suggest it.

**Comment by kentcdodds** [comment]
Ah, good ideas.

I think let's start with the suggestion from @puemos. Not sure how I feel about @baruchvlz's idea. I worry it could lead to confusion and potentially hide problems 🤔

**Comment by baruchvlz** [comment]
@kentcdodds Yea, I agree that it could lead to confusion. It also feels like it's trying to solve one specific scenario which doesn't go at-par with the library. In any case, I still wanted to suggest it 😃

**Comment by kentcdodds** [comment]
This fix by @puemos will be released momentarily! Thanks!

**Comment by alexkrolick** [comment]
I think their might be differences in how browsers fire keypress events - I don't see handleKeyPress being called at all when I type in the codesandbox on mobile Chrome. `onKeyDown`/`onKeyUp` do get called.

**Comment by Jacknes** [comment]
For me, using fireEvent.keyDown all I needed to add was the keyCode

` fireEvent.keyDown(searchField, { key: 'enter', keyCode: 13 })`

**Comment by ryota-murakami** [comment]
I had still same issue at 'keyPress' event on the personal open-source project.🤔
- version: @testing-library/react@8.0.4

#### Relevant code

```diff
test('should work edit mode toggle', () => {
  const { getByTestId, container } = render(
    <Provider store={initialStore}>
      <App />
    </Provider>
  )

  // by default, edit input form is not visible
  expect(getByTestId('todo-edit-input')).not.toBeVisible()

  // double click todo text label, then enable todo text edit code
  fireEvent.doubleClick(getByTestId('todo-body-text'))
  expect(getByTestId('todo-item')).toHaveClass('editing')
  // @TODO in jsdom, dynamic .editing css class doesn't apply. So tipically show/hide UI test are difficult.
  // @ref https://spectrum.chat/testing-library/general/testing-an-accordion~b004a9b1-b104-4eb1-a73b-43c60b1a3630?m=MTU1NDQ4NDIzMTQ5Ng==
  //expect(getByTestId('todo-edit-input')).toBeVisible()
  fireEvent.change(getByTestId('todo-edit-input'), {
    target: { value: 'cut tomato plus' }
  })
+  //@TODO why fireEvent.keyPress() didn't work?
+  fireEvent.keyPress(getByTestId('todo-edit-input'), {
+  key: 'Enter',
+  code: 13,
  })

expect(getByTestId('todo-body-text')).toHaveTextContent('cut tomato plus')
+ success press enter key then finish edit mode
+ expect(container.querySelector('[class*="editing"]')).toBe(null)
```

But added `keyCode: 13` option, it works well.

Bellow, I left reproduce log.

- picture(commit)
<img width="944" alt="Screen Shot 2019-08-17 at 11 31 33" src="https://user-images.githubusercontent.com/5501268/63205675-d7f7e480-c0e2-11e9-893c-516a0634fb23.png">

- [Line of test target onKeyPress event](https://github.com/ryota-murakami/react-typescript-todo-example-2019/blob/18ce7134c4e9fb030eb9881e000233dbbd4a0cbe/src/App/Item/index.tsx#L118)

- [onKeyPress callback function](https://github.com/ryota-murakami/react-typescript-todo-example-2019/blob/18ce7134c4e9fb030eb9881e000233dbbd4a0cbe/src/App/Item/index.tsx#L26-L32).  

- [Commit Log with carCode](https://github.com/ryota-murakami/react-typescript-todo-example-2019/commit/7c54d9f9754c51e4976b34c00ccec3846e3a2f63) and [CILink](https://circleci.com/gh/ryota-murakami/react-typescript-todo-example-2019/372?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

- [Commit Log without carCode](https://github.com/ryota-murakami/react-typescript-todo-example-2019/commit/44b4f635284beb2173f20485228c067dfa8f1f0a) and [CI  Link](https://circleci.com/gh/ryota-murakami/react-typescript-todo-example-2019/367?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

to: @kentcdodds @puemos

**Comment by sstauross** [comment]
> ng fireEvent.keyDown all I needed to add was the keyCode

Had same issue with enter and using _keyCode_ instead of _code_ worked:
```
    fireEvent.keyDown(domElement, {
      key: 'Enter',
      keyCode: 13,
    });
```

**Comment by wunnle** [comment]
I'm still having the same problem, couldn't manage to fire 'Enter' to submit the form. 

I tried different suggestions from here, with keyCode instead of code and/or adding charCode, none of them worked for me.

**Comment by thiemnv-teko** [comment]
Same issue with my code:
`const inputText = 'z'.repeat(254);
    let outputText = '';

    const comp = queryByTestId('name');

    fireEvent.change(comp , { target: { value: inputText } });
    fireEvent.keyPress(comp , { key: 'A', keyCode: 65 });
    fireEvent.keyPress(comp , { key: 'A', keyCode: 65 });
    outputText = ref.current.getData().name; // forwardRef, useImperativeHandle here

    expect(outputText.length).toEqual(255);`

outputText length still 254

**Comment by ThomasBurleson** [comment]
This still seems to be a bug (even in version 9.4.0). Should this be re-opened?

**Comment by kentcdodds** [comment]
Please open a new issue with a reproduction and a suggested solution.

**Comment by SimonFinney** [comment]
Is this still an issue that folks are having? I've attempted the solutions above and have been unable to resolve.

**Comment by eps1lon** [comment]
> I'm still having the same problem, couldn't manage to fire 'Enter' to submit the form.

@wunnle  As far as I know this is a limitation of JSDOM. That a form is submitted when pressing `Enter` while an input is focused is not standard (as in there is no specification for that) behavior. 

Most browsers implement it anyway. 

Someone would need to do a bit of research and find out if this is expected (as in the browser also ignores dispatched Enter) or if this is indeed only a JSDOM limitation.

Otherwise it might make sense to propose this feature to `user-event.`

**Comment by brietsparks** [comment]
In all the confusion I'm seeing variance in:

- `.keyDown`, `.keyPress`
- `key`: `'enter'`, `'Enter'`
- `keyCode` and `code`: `13` and [`Enter`](https://testing-library.com/docs/dom-testing-library/api-events)

So I ran:

```
fireEvent.keyDown(input, { key: 'Enter', keyCode: 13 });
fireEvent.keyDown(input, { key: 'enter', keyCode: 13 });
fireEvent.keyDown(input, { key: 'Enter', code: 13 });
fireEvent.keyDown(input, { key: 'enter', code: 13 });

fireEvent.keyDown(input, { key: 'Enter', keyCode: 'Enter' });
fireEvent.keyDown(input, { key: 'enter', keyCode: 'Enter' });
fireEvent.keyDown(input, { key: 'Enter', code: 'Enter' });
fireEvent.keyDown(input, { key: 'enter', code: 'Enter' });

fireEvent.keyDown(input, { key: 'Enter', keyCode: 'enter' });
fireEvent.keyDown(input, { key: 'enter', keyCode: 'enter' });
fireEvent.keyDown(input, { key: 'Enter', code: 'enter' });
fireEvent.keyDown(input, { key: 'enter', code: 'enter' });

fireEvent.keyPress(input, { key: 'Enter', keyCode: 13 });
fireEvent.keyPress(input, { key: 'enter', keyCode: 13 });
fireEvent.keyPress(input, { key: 'Enter', code: 13 });
fireEvent.keyPress(input, { key: 'enter', code: 13 });

fireEvent.keyPress(input, { key: 'Enter', keyCode: 'Enter' });
fireEvent.keyPress(input, { key: 'enter', keyCode: 'Enter' });
fireEvent.keyPress(input, { key: 'Enter', code: 'Enter' });
fireEvent.keyPress(input, { key: 'enter', code: 'Enter' });

fireEvent.keyPress(input, { key: 'Enter', keyCode: 'enter' });
fireEvent.keyPress(input, { key: 'enter', keyCode: 'enter' });
fireEvent.keyPress(input, { key: 'Enter', code: 'enter' });
fireEvent.keyPress(input, { key: 'enter', code: 'enter' });
```

And found that my winning combo of the day was `fireEvent.keyPress(input, { key: 'Enter', keyCode: 13 });`

Don't know if it covers all permutations but you get the idea

**Comment by rohmanhm** [comment]
It seems this issue is related to https://github.com/testing-library/react-testing-library/issues/680

**Comment by lannyheidbreder-mc** [comment]
> And found that my winning combo of the day was fireEvent.keyPress(input, { key: 'Enter', keyCode: 13 });

Naturally, the winning combo uses a deprecated event with a big red warning on MDN 😅

**Comment by ryota-murakami** [comment]
Over a year I was facing and commented issue still arrive. This is interesting.
Here is looks like domevent-debugging-library lol

**Comment by thinkty** [comment]
I think this has been a while but I was also facing this problem and tried all the approaches mentioned in this thread but was not able to solve it. However, I was able to finally solve using [user-event](https://github.com/testing-library/user-event).
I'm not sure of the exact technical differences between the [userEvent.type](https://github.com/testing-library/user-event#typeelement-text-options) and fireEvent.keyPress that makes userEvent work but i think it is worth taking a look.

**Comment by wafuwafu13** [comment]
I solved by
```ts
import userEvent from '@testing-library/user-event';

input.focus();
userEvent.keyboard('{enter}');
```

**Comment by davidcoelho02** [comment]
This is still not working... the event itself is fired, but the state doesn't change. 
I've tried it with fireEvent.keyDown and fireEvent.keyPress.

**Comment by davidcoelho02** [comment]
It worked with @wafuwafu13 solution 💪

**Comment by yduartep** [comment]
> I solved by
> 
> ```ts
> import userEvent from '@testing-library/user-event';
> 
> input.focus();
> userEvent.keyboard('{enter}');
> ```

This is also working for me

**Comment by elmijo** [comment]
Hi guys,  I think the issue happens because the focus is not on the input, so if you do this:

```js
input.focus()
fireEvent.keyPress(input, { key: 'Enter', keyCode: 13 });
```
The keyboard event will be fired. At latest it worked for me 😄 

- @testing-library/react: 14.0.0
- Node.js 16.18.1
